name: 👋 Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hello there 👋
          Thanks for submitting your first issue to the Retro Home project 🐛 We'll try and take a look at your issue soon ⏲

          In the meantime you might want to join the [Wimpy's World Discord](https://wimpysworld.io/discord) 🗣 where we have a large community of Linux 🐧 enthusiasts and passionate open source developers 🧑‍💻 and a support channel for this project.

          You might also be interested in following [Wimpy's World Twitch 📡 channel](https://twitch.tv/WimpysWorld) where Wimpy streams let's code videos, including this project, several times a week. A back catalog of past live streams and other Linux 🐧 and Raspberry Pi 🥧 related content is available on [Wimpy's World YouTube 📺 channel](https://youtube.com/WimpysWorld).
        pr-message: |
          Hello there 👋
          Thanks for submitting your first pull request to the Retro Home project 💪 We'll try to review your pull request soon ⏲

          In the meantime you might want to join the [Wimpy's World Discord](https://wimpysworld.io/discord) 🗣 where we have a large community of Linux 🐧 enthusiasts and passionate open source developers 🧑‍💻 and a support channel for this project.

          You might also be interested in following [Wimpy's World Twitch 📡 channel](https://twitch.tv/WimpysWorld) where Wimpy streams let's code videos, including this project, several times a week. A back catalog of past live streams and other Linux 🐧 and Raspberry Pi 🥧 related content is available on [Wimpy's World YouTube 📺 channel](https://youtube.com/WimpysWorld).
